---
# This playbook deploys jenkins

- name: install packages utils all nodes
  hosts: all
#  remote_user: johcarte
  remote_user: root
  roles:
    - common

- name: install java on all nodes
  hosts: all
  remote_user: root
  roles:
    - java

- name: install jenkins
  hosts: all
  remote_user: root
  roles:
    - jenkins
