---

# #      ['https://pkg.jenkins.io/redhat-stable', 'https://pkg.jenkins.io/redhat-stable/jenkins.io.key']

- name: Ensure Jenkins repo is installed.
  get_url:
    url: "https://pkg.jenkins.io/redhat-stable"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "https://pkg.jenkins.io/redhat-stable/jenkins.io.key"
