---
# This playbook contains plays that set up the repositories for jenkins and installs jenkins

- import_tasks: configure_yum_repo.yml
  when: ansible_os_family == "RedHat"

- import_tasks: configure_apt_repo.yml
  when: ansible_os_family == "Debian"

#      ['https://pkg.jenkins.io/debian-stable', 'https://pkg.jenkins.io/debian-stable/jenkins.io.key']
#      ['https://pkg.jenkins.io/redhat-stable', 'https://pkg.jenkins.io/redhat-stable/jenkins.io.key']


- name: install jenkins on redhat based systems
  yum: name=jenkins state=present
  tags: jenkins
  when: ansible_os_family == "RedHat"

- name: install jenkins on debian based systems
  apt: name=jenkins state=present
  tags: jenkins
  when: ansible_os_family == "Debian"

#Start/Stop jenkins
- name: Start jenkins service
  service:
    name: jenkins
    state: started

# - name: Wait for Jenkins to start up
#   uri:
#     url: http://localhost:8080
#     status_code: 200
#     timeout: 5
#   register: jenkins_service_status
#   # Keep trying for 5 mins in 5 sec intervals
#   retries: 60
#   delay: 5
#   until: >
#      'status' in jenkins_service_status and
#      jenkins_service_status['status'] == 200

# see https://stackoverflow.com/questions/42219781/gets-error-cannot-get-csrf-when-trying-to-install-jenkins-plugin-using-ansible
# - import_tasks: jenkins_plugins.yml
